version: '2'
services:
  web:
    image: tomcat:8
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes:
      #- ./out/artifacts/ROOT/ROOT.war:/usr/local/tomcat/webapps/ROOT.war:z
      #- ./out/artifacts/Richkware_Manager_Server/Richkware-Manager-Server.war:/usr/local/tomcat/webapps/Richkware-Manager-Server.war:z
      #- ./target/Richkware-Manager-Server :/usr/local/tomcat/webapps/Richkware-Manager-Server_EXP:z
      - ./target/Richkware-Manager-Server.war :/usr/local/tomcat/webapps/Richkware-Manager-Server.war:z

    #restart: always
    #restart: on-failure

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=richk
      - MYSQL_DATABASE=richkware
      - MYSQL_USER=richk
      - MYSQL_PASSWORD=richk